#' Evaluate the network with ENLIGHT trials
#'
#' Use the synthetic lethal network to give each patient in the ENLIGHT trials a score according to their genetic expression and evaluate whether that prediction matches the real ouctcome
#'
#' @param SL_pairs tibble generated by create_network(). The synthetic lethal network to use for evaluation
#' @param synthetic_rescue boolean. Whether to use the concept of synthetic rescue for prediction
#' @param parallel boolean. Whether to use parallel computing to increase speed.
#'
#' @param tissue string. Only trials with a tumor in this type of tissue will be considered: `"all"` (the default), `"breast"`, `"lung"`, and others.
#'
#' @return A list containing the predictions for each patient and their real outcome, plots of these results, and the results of statistical tests
#' @export
#'
#' @examples
#' validate_enlight(SL_pairs)
#' validate_enlight(SL_pairs, tissue = "breast")
#'
validate_ctrpv2 <- function(SL_pairs,
                            synthetic_rescue = TRUE,
                            parallel = TRUE,
                            SL_pairs_method = "filtered",
                            tissue = "all",
                            n = 30,
                            filter = TRUE,
                            SR_pairs = tibble(),
                            title = "SL") {
  library(rstatix)
  library(tictoc)
  library(tidyverse)
  
  datapath <- file.path(getwd(), "data")
  
  
  
  
  if (filter) {
    SR_pairs <-  SL_pairs |> dplyr::filter(
      SR_DD_q_value < 0.01,
      SR_DD_depletion_q_value < 0.01,
      phylo_coefficient < 10.5,
      phylo_coefficient > 0,
      survival_coef < 0
    ) |>
      group_by(gene1) |>
      slice_max(survival_coef, n = n) #The ones with the most negative
    
    
    SL_pairs <-  SL_pairs |>
      group_by(gene1) |>
      slice_min(survival_coef, n = n) |> 
      dplyr::filter(
      q_value < 0.01,
      depletion_q_value < 0.01,
      phylo_coefficient < 10.5,
      phylo_coefficient > 0,
      survival_coef < 0
    ) #USe the same boundary for the phylogenetic coefficient as ISLE
     #The ones with the most negative
    
  }
  
  
  drug_targets_path <- file.path(datapath, 'drug_targets_ctrpv2.csv')
  drug_targets <- read_csv(drug_targets_path) |>
    mutate(genes = str_split(genes, ","))
  
  
  
  
  
  if (parallel) {
    library(doParallel)
    cl <- makeCluster(max(detectCores() - 2, 1))
    registerDoParallel(cl)
  }
  # plots <- list()
  # tests <-  tibble(trial = character(), p_value = numeric())
  # trials_scores <- tibble(
  #   trial = character(),
  #   sample_ID = character(),
  #   score = numeric(),
  #   Response = character()
  # )
  trials_scores <- list()
  plots <- list()
  tests <-  tibble(trial = character(), p_value = numeric())
  for (i in 1:nrow(drug_targets)) {
    #First must be fixed because it is two drugs
    drug <- drug_targets$drug[i]
    genes <- drug_targets$genes[i][[1]]
    print(drug)
    print(genes)
    #make list of all matching dataset files and make for loop for all paths
    
    if(drug != "Tipifarnib"){
    #Tipifarnib has problems with the patient indices
    trial_scores <-
      calculate_score_ctrpv2(
        drug,
        genes,
        SL_pairs_method,
        parallel,
        synthetic_rescue = synthetic_rescue,
        SL_pairs = SL_pairs,
        SR_pairs = SR_pairs
      )
    print(i)
    
    
    
    
    
    if(max(trial_scores$score) > 0){
    # plots[[drug]] <- plot
    # tests <- tests |> add_row(trial = drug, p_value = test$p.value)
    #trials_scores <- trials_scores |>  add_row(trial = trial_scores$Dataset, sample_ID = trial_scores$sample_ID, score = trial_scores$score, Response = trial_scores$Response )
      trials_scores[[drug]] <- trial_scores
    }
    
  }
  
  
  }
  
  
  #q_value <- p.adjust(tests$p_value, method = "fdr")
  
  
  
  if (parallel) {
    stopCluster(cl)
  }
  
  
  
  return( trials_scores
  )
  
}
