#' Evaluate the network with ENLIGHT trials
#' 
#' Use the synthetic lethal network to give each patient in the ENLIGHT trials a score according to their genetic expression and evaluate whether that prediction matches the real ouctcome
#'
#' @param SL_pairs tibble generated by create_network(). The synthetic lethal network to use for evaluation
#' @param synthetic_rescue boolean. Whether to use the concept of synthetic rescue for prediction
#' @param parallel boolean. Whether to use parallel computing to increase speed.
#' @param SL_pairs_method 
#' @param tissue string. Only trials with a tumor in this type of tissue will be considered: `"all"` (the default), `"breast"`, `"lung"`, and others.
#'
#' @return A list containing the predictions for each patient and their real outcome, plots of these results, and the results of statistical tests
#' @export
#'
#' @examples
#' validate_enlight(SL_pairs)
#' validate_enlight(SL_pairs, tissue = "breast")
#' 
validate_enlight <- function(SL_pairs, synthetic_rescue = FALSE, parallel = TRUE, SL_pairs_method = "filtered", tissue = "all", n = 20, filter = FALSE, SR_pairs = tibble(), title = "SL"){
library(rstatix)
library(tictoc)
library(tidyverse)
library(ggpubr)

  datapath <- file.path(getwd(), "data")


if (filter){
SR_pairs <-  SL_pairs |> dplyr::filter(SR_DD_q_value < 0.05, SR_DD_depletion_q_value < 0.05) |> 
  group_by(gene1) |> 
  slice_max(survival_coef, n = n) #The ones with the most negative


SL_pairs <-  SL_pairs |>   group_by(gene1) |> 
  dplyr::filter(q_value < 0.1, depletion_q_value < 0.1, phylo_coefficient < 10.5, phylo_coefficient > 0) |>  #USe the same boundary for the phylogenetic coefficient as ISLE
  slice_min(survival_coef, n = n) #The ones with the most negative

}


if (title == "SL") {
  SL_pairs <-  SL_pairs |>   group_by(gene1) |> slice_min(survival_coef, n = n) |> ungroup()
}

drug_targets_path <- file.path(datapath, 'drug_targets.csv')
drug_targets <- read_csv(drug_targets_path) |>
  mutate(genes = str_split(genes, ","))





if (parallel) {
  library(doParallel)
  cl <- makeCluster(max(detectCores() - 2, 1))
  registerDoParallel(cl)
}
plots <- list()
tests <-  tibble(trial = character(), p_value = numeric())
trials_scores <- tibble(trial = character(), sample_ID = character(), score = numeric(), Response = character())
for (i in 2:nrow(drug_targets)) {
  #First must be fixed because it is two drugs
  drug <- drug_targets$drug[i]
  genes <- drug_targets$genes[i][[1]]
  targeted_tissue <- drug_targets$tissue[i]
  print(drug)
  print(genes)
  #make list of all matching dataset files and make for loop for all paths
  
  if (i != 22 &
      i != 23 & i!=6  & i!=7  & i!=8 & i!=9 & i!=19 & (tissue == "all" | tissue == targeted_tissue)) { #VEGFA DOESNT EXIST in the gene_effect, could make it so it considers VEGFA for expression
    #Tipifarnib has problems with the patient indices 
    trial_scores <-
      calculate_score(drug, genes, SL_pairs_method, parallel, synthetic_rescue = synthetic_rescue, SL_pairs = SL_pairs, SR_pairs = SR_pairs)
    print(i)
    
    
    test <- wilcox.test(score ~ Response, data = trial_scores, alternative = "less", var.equal = TRUE)
    
    
    #Plot
    
    plot <- trial_scores |>
      group_by(Response) |>
      ggplot(aes(
        x = Response,
        y = score,
        group = Response,
        fill = Response
      )) +
      geom_boxplot() +
      stat_summary(
        fun.data = get_box_stats,
        geom = "text",
        hjust = 0.5,
        vjust = 0.9
      ) +
      geom_dotplot(binaxis = 'y',
                   stackdir = 'center',
                   dotsize = 1) +
      # geom_text(data = means, aes(label = weight, y = weight + 0.08)) +
      ggtitle(
        str_c(
          "Plot of the Clinical Trial ",
          drug, "    p-value = ", round(test$p.value,3)
        )
      ) +
      theme(plot.title = element_text(hjust = 0.5)) +
      # labs(caption = 
      #      str_c("Synthetic lethal pairs obtained via the method ",
      #      "Binarize expression")) +
      xlab("Response to treatment") + ylab("Synthetic Lethality Score") 
    
    
    #print(plot)

    #Tests 

    # trial_scores  |>   #Check normality (Comprova que funcioni)
    #   group_by(Response)  |>
    #   shapiro_test(score)
    # 
    # 
    # trial_scores |>       #Check outliers
    #   group_by(Response) |>
    #   identify_outliers(score)
    # 
    # trial_scores |>  levene_test(score ~ Response)  #Check equal variances

   




    
    
    #trials_scores[[drug]] <- trial_scores
    
    if(max(trial_scores$score) > 0){
      plots[[drug]] <- plot
    
    tests <- tests |> add_row(trial = drug, p_value = test$p.value)
    trials_scores <- trials_scores |>  add_row(trial = trial_scores$Dataset, sample_ID = trial_scores$sample_ID, score = trial_scores$score, Response = trial_scores$Response )
    }
    
  }
}


q_value <- p.adjust(tests$p_value, method = "fdr")

tests <-
  tests |> add_column(q_value = q_value)


stat.test <- trials_scores %>%
  group_by(trial) %>%
 wilcox_test(score ~ Response, alternative = "less") %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance("p.adj")
stat.test

stat.test

stat.test <- stat.test |> mutate(y.position = 1, p.adj = round(p.adj, 3))

stat.test <- stat.test |> mutate(.y. = "score", group1 = "Non-responder", group2 = "Responder")




stat.test <- stat.test %>%
  add_xy_position(x = "trial")



plot <- trials_scores |>
  group_by(Response) |>
  ggboxplot(
    x = "trial",
    y = "score",
    fill = "Response",
    palette = c( "darkred", "#73a9c9"),
    color = "black",
    add = "dotplot",
    add.params = list(size = 0.4, alpha = 1)
  ) +
  stat_pvalue_manual(
    stat.test,  label = "p.adj", tip.length = 0,
    remove.bracket = TRUE, size = 5
  )+
  # geom_text(data = means, aes(label = weight, y = weight + 0.08)) +
  # ggtitle(
  #   str_c(
  #     "Plots of the ", title, " scores of clinical trials"
  #   )
  # ) +
  # theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Trial") + ylab("Synthetic Lethality Score") + rotate_x_text(15) +
  font("xlab", size = 14)+
  font("ylab", size = 14)+
  font("x.text", size = 14)+
  font("y.text", size = 14)

plot <- ggpar(plot, font.legend = c(14, "plain", "black"))

print(plot)



if (parallel){
  stopCluster(cl)
}



return(list("tests" = tests, "plots" = plots, "trials_scores" = trials_scores))
}